import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import AdmZip from 'adm-zip';
import { importMcpBundle } from '../dist/electron/mcp-bundle.mjs';
import { normalizeMcpServers, resolveMcpServer } from '../dist/electron/mcp-config.mjs';
import { McpClient } from '../dist/electron/mcp.mjs';
import { HttpMcpClient } from '../dist/electron/mcp-http.mjs';
import { serializeSettings, deserializeSettings, preserveUndecryptableSecrets } from '../dist/electron/settings.mjs';

const fixture = `process.stdin.setEncoding('utf8'); let buffer=''; process.stdin.on('data',chunk=>{buffer+=chunk; let index; while((index=buffer.indexOf('\\n'))>=0){const msg=JSON.parse(buffer.slice(0,index));buffer=buffer.slice(index+1);if(msg.id==null)continue;const result=msg.method==='initialize'?{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'fixture',version:'1'}}:msg.method==='tools/list'?{tools:[{name:'echo',description:'fixture',inputSchema:{type:'object',properties:{}}}]}:{content:[{type:'text',text:JSON.stringify({cwd:process.cwd(),value:process.env.TEST_VALUE,args:process.argv.slice(2)})}]};process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:msg.id,result})+'\\n');}});`;
const manifest = () => ({manifest_version:'0.3',name:'fixture',version:'1.0.0',description:'fixture',author:{name:'test'},server:{type:'node',entry_point:'server.mjs',mcp_config:{command:process.execPath,args:['${__dirname}/server.mjs','${user_config.paths}'],env:{TEST_VALUE:'${user_config.token}'}}},user_config:{token:{type:'string',title:'令牌',description:'test',required:true,sensitive:true},paths:{type:'directory',title:'目录',description:'test',multiple:true,default:['${HOME}/Documents','/tmp/a b']}}});
async function bundle(t, value=manifest(), extra) { const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dyw-mcp-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const zip=new AdmZip();zip.addFile('manifest.json',Buffer.from(JSON.stringify(value)));zip.addFile('server.mjs',Buffer.from(fixture));extra?.(zip);const file=path.join(dir,'fixture.mcpb');zip.writeZip(file);return {dir,file}; }

test('MCPB 导入后实际启动、发现工具并调用，支持空格路径和数组变量', async t=>{
 const {dir,file}=await bundle(t); const server=await importMcpBundle(file,path.join(dir,'installed'));server.bundle.userConfig.token='sample-secret';server.bundle.userConfig.paths=['/tmp/a b','/tmp/c'];
 const resolved=resolveMcpServer(server);assert.deepEqual(resolved.args.slice(1),['/tmp/a b','/tmp/c']);assert.equal(resolved.env.TEST_VALUE,'sample-secret');
 const client=new McpClient(resolved);t.after(()=>client.close());await client.connect();assert.equal(client.tools[0].name,'echo');const result=await client.callTool('echo',{});const actual=JSON.parse(result.text);assert.equal(actual.cwd,await fs.realpath(server.bundle.directory));assert.equal(actual.value,'sample-secret');assert.deepEqual(actual.args,['/tmp/a b','/tmp/c']);
});
test('MCPB 缺少必填变量、未知变量与循环引用给出错误',async t=>{const {dir,file}=await bundle(t);const server=await importMcpBundle(file,path.join(dir,'installed'));delete server.bundle.userConfig.token;assert.throws(()=>resolveMcpServer(server),/请填写令牌/);server.bundle.userConfig.token='${unknown}';assert.throws(()=>resolveMcpServer(server),/不支持的变量/);server.bundle.userConfig.token='${user_config.token}';assert.throws(()=>resolveMcpServer(server),/循环变量/);});
test('MCPB 平台覆盖生效且不能导入不支持的平台',async t=>{const value=manifest();value.server.mcp_config.platform_overrides={[process.platform]:{env:{OVERRIDE:'yes'}}};const {dir,file}=await bundle(t,value);const server=await importMcpBundle(file,path.join(dir,'installed'));assert.equal(server.env.OVERRIDE,'yes');value.compatibility={platforms:['nonexistent']};const bad=await bundle(t,value);await assert.rejects(importMcpBundle(bad.file,path.join(bad.dir,'installed')),/不支持当前系统/);});
test('MCPB 拒绝启动文件缺失、损坏文件与不支持的版本',async t=>{const value=manifest();value.server.entry_point='missing.mjs';const a=await bundle(t,value);await assert.rejects(importMcpBundle(a.file,path.join(a.dir,'installed')),/缺少启动文件/);value.manifest_version='9.0';const b=await bundle(t,value);await assert.rejects(importMcpBundle(b.file,path.join(b.dir,'installed')),/格式版本/);await fs.writeFile(b.file,'not a zip');await assert.rejects(importMcpBundle(b.file,path.join(b.dir,'installed')));});
test('MCPB 拒绝符号链接，不在安装目录留下文件',async t=>{const {dir,file}=await bundle(t,manifest(),zip=>{zip.addFile('escape',Buffer.from('/tmp')); zip.getEntry('escape').attr = (0o120777 << 16) >>> 0;});await assert.rejects(importMcpBundle(file,path.join(dir,'installed')),/不安全/);await assert.rejects(fs.stat(path.join(dir,'installed')),/ENOENT/);});
test('MCPB 0.4 UV 文件生成启动配置并要求项目文件', async t => {
 const value = manifest(); value.manifest_version = '0.4'; value.server = {type:'uv',entry_point:'server.mjs'};
 const {dir,file} = await bundle(t,value,zip => zip.addFile('pyproject.toml',Buffer.from('[project]\nname="fixture"\nversion="1.0.0"')));
 const server = await importMcpBundle(file,path.join(dir,'installed'));assert.equal(server.command,'uv');assert.equal(server.args[0],'run');assert.equal(resolveMcpServer(server).cwd,server.bundle.directory);
 const missing = await bundle(t,value);await assert.rejects(importMcpBundle(missing.file,path.join(missing.dir,'installed')),/pyproject/);
});
test('本机环境与显式环境变量合并；缺失认证变量不能静默连接',()=>{const resolved=resolveMcpServer({command:'node',env:{LOCAL:'set'},envPassthrough:['INHERITED'],headers:{'X-Custom':'plain'},envHeaders:{'X-Secret':'TOKEN'},bearerTokenEnvVar:'TOKEN'},{PATH:'/bin',INHERITED:'yes',TOKEN:'value'});assert.equal(resolved.env.PATH,'/bin');assert.equal(resolved.env.LOCAL,'set');assert.equal(resolved.headers.Authorization,'Bearer value');assert.equal(resolved.headers['X-Secret'],'value');assert.throws(()=>resolveMcpServer({bearerTokenEnvVar:'MISSING'},{}),/未设置环境变量/);});
test('设置保存后保留两种连接与完整扩展字段，秘密不以明文保存',()=>{const storage={isEncryptionAvailable:()=>true,encryptString:v=>Buffer.from(v).reverse(),decryptString:v=>Buffer.from(v).reverse().toString()};const source={mcpServers:[{id:'local',name:'Local',command:'node',args:['a b'],cwd:'~/code',env:{SECRET:'private-value'},envPassthrough:['HOME'],bundle:{manifest:manifest(),directory:'/tmp/installed',userConfig:{token:'bundle-secret'}}},{id:'http',name:'HTTP',transport:'http',url:'http://127.0.0.1/mcp',command:'',args:[],headers:{Authorization:'private-http'},envHeaders:{'X-Token':'TOKEN'},bearerTokenEnvVar:'TOKEN'}]};const encoded=serializeSettings(source,storage);assert.equal(encoded.mcpServers.length,2);assert.ok(!JSON.stringify(encoded).includes('private-value'));assert.ok(!JSON.stringify(encoded).includes('bundle-secret'));assert.ok(!JSON.stringify(encoded).includes('private-http'));const decoded=deserializeSettings(encoded,storage);assert.equal(decoded.mcpServers[0].env.SECRET,'private-value');assert.equal(decoded.mcpServers[0].bundle.userConfig.token,'bundle-secret');assert.equal(decoded.mcpServers[1].headers.Authorization,'private-http');assert.equal(decoded.mcpServers[1].transport,'http');const broken={...storage,decryptString:()=>{throw new Error('locked')}};const reread=deserializeSettings(encoded,broken);assert.throws(()=>resolveMcpServer(reread.mcpServers[0]),/无法读取/);const resaved=preserveUndecryptableSecrets(serializeSettings(reread,storage),encoded,broken);assert.equal(resaved.mcpServers[0].privateConfig,encoded.mcpServers[0].privateConfig);});
test('旧版启动命令设置仍可使用',()=>{const [server]=normalizeMcpServers([{id:'old',command:'node',args:['a b'],enabled:false}]);assert.equal(server.transport,'stdio');assert.deepEqual(server.args,['a b']);assert.equal(server.enabled,false);});

test('流式 HTTP 实际连接、认证标头、分页、工具调用和取消',async t=>{
 const requests=[];
 const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;if(req.method==='GET'){res.writeHead(405).end();return;}const msg=JSON.parse(body);requests.push({msg,headers:req.headers});if(msg.id==null){res.writeHead(202).end();return;}let result;if(msg.method==='initialize'){result={protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'HTTP fixture',version:'1'}};}else if(msg.method==='tools/list'){result=msg.params.cursor?{tools:[{name:'second',inputSchema:{type:'object'}}]}:{tools:[{name:'echo',inputSchema:{type:'object'}}],nextCursor:'next'};}else if(msg.params.name==='slow'){return;}else result={content:[{type:'text',text:msg.params.arguments.value}]};res.writeHead(200,{'Content-Type':'application/json',...(msg.method==='initialize'?{'Mcp-Session-Id':'session-test'}:{})});res.end(JSON.stringify({jsonrpc:'2.0',id:msg.id,result}));});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();server.close();});const config=resolveMcpServer({transport:'http',url:`http://127.0.0.1:${server.address().port}/mcp`,bearerTokenEnvVar:'TOKEN',envHeaders:{'X-Test':'TOKEN'}},{TOKEN:'sample'});const client=new HttpMcpClient(config);t.after(()=>client.close());await client.connect();assert.deepEqual(client.tools.map(tool=>tool.name),['echo','second']);const result=await client.callTool('echo',{value:'actual response'});assert.equal(result.text,'actual response');assert.equal(requests[0].headers.authorization,'Bearer sample');assert.equal(requests[0].headers['x-test'],'sample');assert.equal(requests.at(-1).headers['mcp-session-id'],'session-test');const controller=new AbortController();const pending=client.callTool('slow',{}, {signal:controller.signal});controller.abort();await assert.rejects(pending);await client.close();assert.equal(client.connected,false);
});
